from django.urls import path
from . import views

urlpatterns = [
    path('', views.UserAPI.as_view()),
    path('student-login/', views.StudentLoginAPI.as_view()),
    path('parent-login/', views.ParentLoginAPI.as_view()),
    path('coach-login/', views.CoachLoginAPI.as_view()),
    path('pschologist-login/', views.PLoginAPI.as_view()),
    path('verify-login/', views.VerifyPhoneAPI.as_view()),
    path('card-create/', views.CardCreateAPI.as_view()),
    path('card-verify/', views.CardVerifyAPI.as_view()),
    path('rate-student/', views.StudentRatePayAPI.as_view()),
    path('rate-parent/', views.ParentRatePayAPI.as_view()),
    path('subscribe-student/', views.SubscribeStudentAPI.as_view()),
    path('subscribe-parent/', views.SubscribeParentAPI.as_view()),
    path('done-exercises/', views.DoneExerciseAPI.as_view()),
    path('notifications/', views.NotificationAPI.as_view()),
    path('my-plan-moduls/', views.MyPlanModulsAPI.as_view()),
    path('my-plan-themes/<int:pk>/', views.MyPlanThemesAPI.as_view()),
    path('my-plan-exercises/', views.MyPlanExercisesAPI.as_view()),
    path('ages/', views.AgeAPI.as_view()),
    path('levels/', views.LevelAPI.as_view()),
    path('request-join/', views.RequestJoinAPI.as_view()),
    path('join/', views.JoinAPI.as_view()),
    path('qr-join/', views.QrJoinAPI.as_view()),
    path('my-children/', views.MyChildrenAPI.as_view()),
    path('my-child-plan/<int:pk>/', views.MyChildPlanAPI.as_view()),
    path('rating/', views.RatingAPI.as_view()),
    path('exercise-answer/', views.ExerciseAnswerAPI.as_view()),
    path('set-point/<int:pk>/', views.PointExerciseAPI.as_view()),
    path('student-plan/<int:pk>/', views.StudentPlanAPI.as_view()),
    path('coach-students-rating/', views.CoachStudentsRatingAPI.as_view()),
    path('pschologist-students-rating/', views.PsychologicalStudentsRatingAPI.as_view()),
    path('student-lesson/', views.LessonStudentAPI.as_view()),
    path('coach-lesson/', views.LessonCoachAPI.as_view()),
    path('pschologist-lesson/', views.LessonPsychologicalAPI.as_view()),
    path('feedback/', views.FeedbackAPI.as_view()),
    path('chat-room/', views.ChatRoomAPI.as_view()),
    path('student-chats/', views.StudentChatAPI.as_view()),
    path('parent-chats/', views.ParentChatAPI.as_view()),
    path('coach-chats/', views.CoachChatAPI.as_view()),
    path('pschologist-chats/', views.PsychologistChatAPI.as_view()),
]
