# Generated by Django 4.2.5 on 2023-10-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexerciseanswer',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='userexerciseanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExercise',
        ),
        migrations.DeleteModel(
            name='UserExerciseAnswer',
        ),
    ]
