# Generated by Django 4.2.5 on 2023-11-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_modul_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='image',
            field=models.ImageField(upload_to='moduls'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(upload_to='themes'),
        ),
    ]
