# Generated by Django 4.2.5 on 2023-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_modul_image_alter_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises'),
        ),
    ]
