# Generated by Django 4.2.5 on 2023-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/images'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(upload_to='exercises/videos'),
        ),
    ]
