# Generated by Django 4.2.5 on 2023-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_alter_exercise_image_alter_exercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='1', upload_to='exercises/images'),
            preserve_default=False,
        ),
    ]
