# Generated by Django 4.2.5 on 2023-11-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_alter_exercise_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOfSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
